### ISSUE TITLE
Extend GeoDataset to support line and Polygons. 

### ISSUE THREAD

**Issue by couasnonanais** [Deltares/hydromt#177]
Right now, GeoDataset only support Point.
Useful resources: 
> https://twhiteaker.github.io/CFGeom/
> https://pypi.org/project/cf-python/

**Comment by DirkEilander** [comment]
TODO:

- [x] parse GeoDataFrames to GeoDataset
- [x] GeoDataset to netcdf with conversion of geometry to wkt
- [x] parse netcdf with wkt to GeoDataset
- [ ] write unit tests
- [ ] decide on data accessor name (geo instead of vector ?)

Related issue: #177 

**Goal**
- easily work with geometry with associated multidimensional data variables
- compared to the current implementation it should support other than point geometries.

**implementation notes:**
- use "vector" accessor for data array and dataset
- keep vector accessor backwards compatible
- use geometry property to get a geopandas.geoarray for each of the following types
- expose some of the geoarray methods directly as method of vector.
- staticmethods: from_netcfd / from_gdf / from_wkt
- methods for to_gdf / to_netcdf

Types of dataset on which the accessor should work:
```
    Dimensions:      (stations: N, time: NT)
    Coordinates:
      * time         (time) [np.datetime64]
      * stations     (stations) [int]
        lon          (stations) [float]
        lat          (stations) [float]
    Data variables:
        waterlevel   (time, stations) [float]
```

```
    Dimensions:      (stations: N, time: NT)
    Coordinates:
      * time         (time) [np.datetime64]
      * stations     (stations) [int]
        geometry    (stations) [numpy object with geometries]
    Data variables:
        waterlevel   (time, stations)
```

```
    Dimensions:      (stations: N, time: NT)
    Coordinates:
      * time         (time) [np.datetime64]
      * stations     (stations) [int]
        geometry    (stations) [numpy array of wkt str]
    Data variables:
        waterlevel   (time, stations)
```



**Notes on geometry object**
Right now the geometries are saved in the `geometry` object of the GeoDataset as a geopandas.array.GeoArray which is a [numpy duck array](https://docs.xarray.dev/en/stable/internals/duck-arrays-integration.html) type with additional geometry methods. This  does not yet implement the `__array__function__` method and can therefore not yet be integrated into a coordinate or variable of a xarray Dataset. Instead in an xarray Dataset it is reduced to a normal numpy objects array.

**Comment by hboisgon** [comment]
Closed as this is now implemented with support for xy or wkt or geom
