### ISSUE TITLE
throw index errors in all get_data methods if out of bounds

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#181]
Some get_data and to_file methods of DataAdapter classes only give a warning and an empty object rather than an error when bbox or time_tuple is out of range. This may yield unclear error messages later on. 

In general low-level functionality should have clear error messages, which can be escaped (try-except) in higher level methods where needed.

**Comment by hboisgon** [comment]
This issue should have been fixed now. This however creates errors in data_catalog.export_data for sources that do not have data there. would be nice to implement a try except with a warning rather than error, which was previsouly covered by this in the previous behavior:

https://github.com/Deltares/hydromt/blob/0def737fbdf4fa2fb7891c790ad0fbcaebb84733/hydromt/data_catalog.py#L583-L585
