### ISSUE TITLE
Modifying lulc changes the boundary of certain variables within the staticmaps.nc file resulting in missing values

### ISSUE THREAD

**Issue by AlessiaRiveros** [Deltares/hydromt#241]
I uploaded a modified GlobCover map to my default wflow model using the following command:
hydromt update wflow wflow_test_full -o .\wflow_mod_globcover -c setup_lulcmaps -d .\static_maps\GlobCover.yml --opt lulc_fn=globcover -v

Then I ran the wflow model which gave the following error:
[ Info: Set `vertical.maxleakage` using NetCDF variable `MaxLeakage`.
[ Info: Set `vertical.c` using NetCDF variable `c`.
[ Info: Set `vertical.kvfrac` using default value `1.0`.
[ Info: Set `vertical.waterfrac` using NetCDF variable `WaterFrac`.
┌ Error: Wflow simulation failed
│   exception =
│    arrays contains missing values (values equal to the fill values attribute in the NetCDF file)

Visualizing the staticmaps.nc, we saw the WaterFrac variable had some missing values at the boundaries. The same holds for all other land use related variables like RootingDepth, etc.

I tried uploading the new staticmaps.nc here but it gave an error, so I've uploaded it in my postbox: n:\Deltabox\Postbox\Riveros, Alessia\staticmaps.nc

**Comment by DirkEilander** [comment]
@AlessiaRiveros Could it be that at the locations where you see missing values in your staticmap layers your modified globcover map has missing values or values (i.e. landuse clesses) that are not in [the reclassification table](https://github.com/Deltares/hydromt_wflow/blob/main/hydromt_wflow/data/lulc/globcover_mapping.csv)? 

To be able to reproduce the error we would need the original model, the globcover.yml file, and the modified globcover data itself, rather than the output staticmaps.

I'm going to close this issue here as it is related to [hydromt_wflow ](https://github.com/Deltares/hydromt_wflow) and/or the data you use rather than hydromt core. Please check on the above suggestions and feel free to follow up with me on Teams or reopen the issue with new info on hydromt_wflow.
