### ISSUE TITLE
ENH: support clipping in get_data methods for python object

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#335]
### Feature Type
- Changing existing functionality in HydroMT

### Enhancement Description

We recently started to support that get_data (eg get_rasterdataset, get_geodataframe etc) can support passing of python object (eg xarray.Dataset or geopands.geodataframe).

However for now we directly return the object without doing any changes:
https://github.com/Deltares/hydromt/blob/168a1373d871b149204eef5065b8722fda80369c/hydromt/data_catalog.py#L624-L655

Could we maybe support doing some transformation tough?
For eg in get_rasterdataset that if variables or time_tuple or single_var_as_array arguments are provided that this is also applied to the passed xr.Dataset? Else you have to do it in your script anyway so that could save some duplicated code if the get_data method could support this.

### Additional Context

An example where this can be useful is we are now developping some generic setup methods like setup_maps_from_raster.
Ideally model plugins could then do some pre-processing (eg compute a new variable) and then directly call the generic setup_methods which starts with a get_rasterdataset to re-harmonize the transformed data.

**Comment by Tjalling-dejong** [comment]
In order to support object transformation in get_data we would need to split the pre-processing part of get_data and create two separate generic functions. One for GeoDataFrame and DataFrame and one for RasterDataset and GeoDataset. These functions are then called in the get_data method of the data adapter classes and called when passing a python object directly in get_rasterdataset, get_geodataset, etc.

**Comment by savente93** [comment]
each of the get_*() functions of the data catalog class. The get_data methods of the adapters have functionality that isn't being applied to objects, so that should be refactored. They do all of their reading, slicing and uniformizing at once, so this is not reusable. We should first refactor these methods to use more modular functions, so that we can also apply those functionalities if we get passed an object which has already read the data, or doesn't have a catalog entry associated meaning that we can't do things like renaming that get specified there.
