### ISSUE TITLE
BUG: Memory error when loading large raster datasets clipped to a geometry

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#350]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.   
- [X] I have checked that this bug exists on the main branch of HydroMT.            

### Issue Description

When loading a rasterdataset clipped with a geom we get memory errors for large datasets because of the `geometry_mask` in `raster.clip_geom` method, see [raster.py#L1157](https://github.com/Deltares/hydromt/blob/e4edd37a19f89bd99614782272864bad58527b27/hydromt/raster.py#L1157) With HydroMT-SFINCS we use many highres datasets which currently are impacted by this bug.

TODO
- [ ] Analyze what impact it has further downstream to remove the geometry_mask in `raster.clip_geom`.
- [ ] Use `clip_bbox` instead of `clip_geom` in the `RasterDatasetAdapter.get_data` method. The bbox can be calculated as `bbox = geom.to_crs(4326).total_bounds`.

### Reproducible Example

```
from hydromt import DataCatalog 
from shapely.geometry import box
import geopandas as gpd

bbox = [-90, 10, -70, 50]
gdf = gpd.GeoDataFrame(geometry=[box(*bbox)], crs=4326) 
cat = DataCatalog(r"deltares_data")
da0 = cat.get_rasterdataset("esa_worldcover", bbox=bbox) # no error
da1 = cat.get_rasterdataset("esa_worldcover", geom=gdf) # memory error
```

### Installed Versions

hydromt 0.7.1

**Comment by savente93** [comment]
I've briefly looked into this and there are a few solutions in ascending order of complexity that I can think of that might be able to alleviate this problem. The problem seems to be that, as far as I can tell, the `clip_geom` has to allocate an entire `numpy` array at the highest resolution everywhere (though it does seem to clip to the bounding box of the geometry first which is good) Taking that into account we could: 
1. see if we can use a chucked dask array instead of a numpy one so the entire array doesn't have to be allocated at once
2. see if some kind of sparse representation would be workable (instead of a full grid of booleans, essentially a matrix containing only the pixels for which there is a collision).
3. check if the geometries are connected with some bounding box analysis, and if not, split each connected sub geometry into it's own mask. I'm basically taking some inspiration here from a QuadTree 

In the mean time there is one other nicety we could do which is, try to clip with the geom, catch the memory error if it occurs, then fall back to the bounding box clip and throw a warning. Possibly with an option for the user to simply hard fail on the memory error if they want (for example for debugging) 

Can anyone with more domain knowledge than me look at the above solutions and tell me which would or would not be acceptable? If you have any questions, but sure to ask them!

**Comment by DirkEilander** [comment]
Thanks for looking into this. 

Option 1 could work if it is possible to use a dask array in the `raster.rasterize` at [raster.py#L1219](https://github.com/Deltares/hydromt/blob/e4edd37a19f89bd99614782272864bad58527b27/hydromt/raster.py#L1219)

Another option would be to just move line [raster.py#1157](https://github.com/Deltares/hydromt/blob/main/e4edd37a19f89bd99614782272864bad58527b27/raster.py#L1157) that calls a geometry_mask in `clip_geom` to within the if-statement on the next line. This would change the behaviour (which likely affects some methods in hydromt_wflow), but would actually be more logical behaviour for this function.

Perhaps we can even do both options.

**Comment by savente93** [comment]
Tried it out and while it's possible to switch to dask arrays it doesn't seem to help, apparently it doesn't apply chuncking like that on it's own. The second solution does resolve the issue though. Given all that I think it makes most sense to just go with the second option you mentioned since the dask array doesn't seem to do much.

**Comment by DirkEilander** [comment]
OK. Let's go with that option. It would be good to alsobopen an issue at hydromt_wflow to assess the impact before merging this into main / release. 

We could also look into using xarray map_blocks for functions like rasterize to parallelize per chunck. https://docs.xarray.dev/en/stable/generated/xarray.Dataset.map_blocks.html
