### ISSUE TITLE
ENH: improve adapter for GeoDataset

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#372]
### Feature Type

- [X] Adding new functionality to HydroMT

- [ ] Changing existing functionality in HydroMT

- [ ] Removing existing functionality in HydroMT

### Enhancement Description

Currently the GeoDataset adapter is quite limited if the files are not in direct netcdf format.
It would be nice to support a little more options:

- fn_data can be netcdf file instead of csv only (we say in the dosctrings it can but this is not the case, see link below)
- fn_data can be a data_catalog entry: this would be handy especially to allow reading options to properly parse csv file (now format as to be exactly what the reader requires)
- fn_data can be multiple (csv) files: for now geodataset require one file per variable with all IDs but for some data this could be organized as one file per ID (with all variables)

https://github.com/Deltares/hydromt/blob/0def737fbdf4fa2fb7891c790ad0fbcaebb84733/hydromt/io.py#L309-L313

### Feature Description

Parts can be implemented in io.open_geodataset and other parts in geodataset.get_data.

**Comment by Tjalling-dejong** [comment]
@DirkEilander I am bit lost on how option 2 was a solution again? This option does not allow for using a datacatalog entry for instance.

**Comment by Tjalling-dejong** [comment]
I moved the third point on multiple fn_data files to a separate issue: #453

**Comment by DirkEilander** [comment]
> @DirkEilander I am bit lost on how option 2 was a solution again? This option does not allow for using a datacatalog entry for instance.

Correct, it is not a solution to the issues, but a way to keep the io.open_geodataset method as a driver next to option 1. However, we need to discuss if we want to keep the open_geodataset method. We also discussed that adding additional drivers to read nc  inside this method is not ideal as it may become very unclear if a user wants to pass arguments to the different drivers. We also agreed passing DataAdapters to an io function is not a good idea. IO methods (a.k.a. drivers) are called from the Adapters and not the other way around.

**Comment by DirkEilander** [comment]
- We keep GeoDatasetAdapter, but only for single files (combined locs and data). This means deprecating the vector driver and the `io.open_geodataset` method. 
- We create a new DatasetAdapter for non-spatial N-Dim data because pandas only works 'nicely' with 2D data. To start with this would support the classic netcdf/zarr and the `io.open_timeseries_from_table` method. The `DataCatalog.get_dataset` methods should have an index argument to filter on.
- Add `{index}`  to resolve path method options, to read files based on index
- We create a new method/driver to read and combine multiple csv files into a single xr.Dataset. This method should get info on how to combine the files based on variables and index.

**Comment by savente93** [comment]
- [ ] fn_data can be netcdf file instead of csv only (we say in the dosctrings it can but this is not the case, see link below)
- [ ] fn_data can be a data_catalog entry: this would be handy especially to allow reading options to properly parse csv file (now format as to be exactly what the reader requires)
- [ ] fn_data can be multiple (csv) files: for now geodataset require one file per variable with all IDs but for some data this could be organized as one file per ID (with all variables)

**Comment by savente93** [comment]
Sorry I'm a bit confused, what are we going to use this new dataset adapter for?

**Comment by savente93** [comment]
Right, sorry. Personally I think that inheritance makes things more complex rather than less. I think that as with the other adapters, the functionality is just different enough to make inheritance not a great idea. I'm personally more in favour of these rules of thum:
1. if it really is generic, put it in the base adapter class
2. if you can create somewhat generic functions do that and then implement the adapters by calling the generic functions (wherever they make the most sense)
3. if it isn't any of the above ones, it's probably different enough to warent it's own implementation.

Does that make sense? That's my take at least, not sure how the others feel.

**Comment by Tjalling-dejong** [comment]
Thanks for the advice!
I will keep the adapters separate and check where I can refactor some of the methods to more generic functions if that is necessary.
