### ISSUE TITLE
DOC: Add a page with tips to start your own plugin

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#375]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Location of the documentation

Somewhere here in a new page/section: https://deltares.github.io/hydromt/latest/dev/intro.html

### Documentation problem

Missing docs

### Suggested fix for documentation

I did a plugin review where I started to explain some things. Some parts could be re-used: https://github.com/Deltares/hydromt_fiat/issues/84

**Comment by savente93** [comment]
I wanted something to do before my conference starts today, so I started working on this. I've made a template repository (https://github.com/savente93/hydromt-plugin-template) so that people wanting a new plugin can just answer a couple of questions and get a starting repository that's similar to hydromt and includes the DSC recommended best practices which should help with interoperability. Since the linting will enforce things like docstrings, this should already take care of some of the problems mentioned in the hydromt fiat review. I will probably need some more help documenting things that are actually related to hydromt but I think this is a nice start. 

I don't have permissions to either make or transfer repos to deltares so I just made one under my own account. If it's is accepted I'll be happy to transfer ownership to the Deltares org. 

WE can add more ideas in the HydroMT docks itself, but I think it will be nice to add them to the template repository as well so that users can have that with their own repo and reference it a bit easier. 

I'm not quite sure what other things are relevant here, and I'm happy to write up some more tips/trics/best practices etc. if someone can help me figure out in a bit more detail what we would like included.

**Comment by DirkEilander** [comment]
Good idea to use cookiecutter! The repos is a great starting point, but should still be accompanied by a docs page as you also mention yourself. 

Some ideas for the template repos
- start a modelclass which inherits from hydromt.Model
- register this class as plugin using the entry point in the pyproject.toml
- add the make_env.py script from the core repos
- align the docs layout with what we use now
- to discuss: follow the _recommended_ best practices are current hydromt core approach for e.g. docs.

Minimal content for the docs page:
- discuss how a plugin in linked to the core ( inheritance and entry points)
- discuss general structure of a model class and read/write functions
- discuss the general structure of setup methods
- explain cookiecutter template

**Comment by savente93** [comment]
To be added in template repo: 
- [ ]  start a modelclass which inherits from hydromt.Model
- [ ]  register this class as plugin using the entry point in the pyproject.toml
- [ ]  add the make_env.py script from the core repos
- [ ]  align the docs layout with what we use now

To be added in the docs of HydroMT itself: 

- [ ] discuss how a plugin in linked to the core ( inheritance and entry points)
- [ ] discuss general structure of a model class and read/write functions
- [ ] discuss the general structure of setup methods
- [ ] explain cookiecutter template

**Comment by savente93** [comment]
I've added everything requested on the repository, and added a docs page explaining the how to use the cookiecutter example. What would still remain is the more in depth explanation of how HydroMT works (the three items in my previous comment that aren't ticked yet). I feel very ill equipped to talk about this. I'm hoping that one of the founders can help with that.

**Comment by savente93** [comment]
@DirkEilander @hboisgon I've added some documentation to the best of my knowledge . Could either of you review it when you have some time? I think I've done as much as I can now, but if more is needed I"m happy to discuss

**Comment by hboisgon** [comment]
Hi @savente93, thanks for the great work on the docs and the template repo! I'm happy to review and add a bit more content to the more in-depth explanation.

**Comment by savente93** [comment]
Let me know if you need push access to the template, I'll add you as a contributor there
