### ISSUE TITLE
Including deperecated dependency group seems to crach pytest

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#410]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

WIP

### Current behaviour

During testing and updating #399 I got random pytest crashes. It seems to be happening when the `deprecated` dependency group is included, but I couldn't pin down exactly what the issue was. More investigation is needed here. 

### Desired behaviour

pytest does not crash

**Comment by DirkEilander** [comment]
@savente93 We have had this issue before which was then bypassed by not checking for the pcraster dependency in _compat.py. Not a good solution at all as is technically blocks use of pcraster... I saw this was undone in [PR407](https://github.com/Deltares/hydromt/pull/407/files#diff-46bfbe743642966051d6d707f0e981627ecb268863436cff0b9a306b44a93702). 
Not sure it's worth putting a lot of effort into fixing this as ideally we remove the dependencies in this group. 

@hboisgon @JoostBuitink Is there still merit in keeping the pcraster read and write functionality in hydromt for old wflow users? If not i'd like this functionality to be deprecated and this large dependency to be removed. Note that since 5 months it already wasn't possible to use pcraster in hydromt and I haven't heard anyone complaining. However, some hydromt-wflow might still be on an older hydromt core version. Note that reverting to an old hydromt version would also be a solution for future wflow pcraster users.

**Comment by hboisgon** [comment]
I guess it can be removed from core but I think then the functionality should move to hydromt_wflow. It is still quite useful to be able to read 'old' wflow models for easy conversion to julia format.

**Comment by JoostBuitink** [comment]
I agree with @hboisgon, it make sense to keep this functionality close the hydromt_wflow. However, I also agree that at some point we do have to deprecate this functionality and tie it to a specific version of hydromt_wflow, as it will remain a large dependency with (I assume) only a limited number of users.

**Comment by savente93** [comment]
well, what we could do is just leave it as an optional dependency and not include that dependency group in the `full` flavour, which would allow people to install it, but leave it largely out of our workflow/environments. The downside of this would be that it will remain untested, at which point imo we might as well remove it all together, but I can't really forsee what consequences that will have. Though it is good to note that indeed, even if we remove it now, it will always remain available in previous versions of HydroMT

**Comment by DirkEilander** [comment]
Let's try excluding the deprecated group from the full flavour for now.

**Comment by DirkEilander** [comment]
@hboisgon and @JoostBuitink we need a decision on this one. Preferably we move the required functionality (mostly reading pcraster files) to hydromt-wflow. Is that OK?
