### ISSUE TITLE
Invalid raster: 2 cells in x dimension

### ISSUE THREAD

**Issue by B-Dalmijn** [Deltares/hydromt#442]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Not quite sure if this qualifies as a bug, but I encountered this when I tried to reproject a DataArray containing only one value in the x dimension, which is possible by just using rasterio.

The following snippet should be enough to reproduce it. This error will also be raised when calling for the transform.

```python
from hydromt.raster import RasterDataArray
from hydromt import open_raster

if __name__ == "__main__":
    ds = open_raster("<ANY RASTER>")
    one_ds = ds.where(ds.x > ds.x[-2],drop=True)
    one_ds.raster.transform
```

### Current behaviour

Raises an error like this:

![image](https://github.com/Deltares/hydromt/assets/92092029/6ff68b13-b894-4650-be52-24eb16a07131)

### Desired behaviour

Not quite sure to what extent the framework allows it, but being able to work with 1D rasters.

**Comment by DirkEilander** [comment]
This is because we always calculate the transform from the raster coordinates and this is simply not possible when one of the spatial dimensions has just one coordinate. With rasterio has to be provided separately. If you use the clip_bbox functionality with a buffer you can avoid this issue in most cases I think. If you think this behaviour should be different can you add some more information on the use case to understand the issue better. I'll close the issue for now, but feel free to reopen it with more context.

**Comment by B-Dalmijn** [comment]
@DirkEilander Your comment was about the fact that you closed this issue, when I reopened I deleted it as the issue is open again. But you're right, I still yet have to refine this. I'll do that on 8-8.

**Comment by B-Dalmijn** [comment]
A possible solution for this could be manually settings the resolution/ geotransform as a backup.
This will more likely lean towards solely setting the geotransform and inferring the resolution from it.

Very basic stuff
```Python
def geotransform(self):
    return self._geotransform

# args to be defined clearly in the actual code
@geotransform.setter
def set_geotransform(self, *args):
    self._geotransform = (*args)
```

Probably we will still lean on the in situ determination of the geotransform (current implementation).
But then we could fall back on a user defined geotransform when the geotransform cannot be determined in situ.

Another option would be to infer it at creation, or setting it from user input and updating it as one e.g. clips the rasterdataset.

```Python
def clip_mask(self, ...):
     # clipping code
     obj_clip = ....
     # updated geotransform components
     obj_clip.raster.set_geotransform(*args)
```

This feels both flexible and not so flexible. It also means that if the user would do some transformations to the raster dataset outside of HydroMT then the geotransform will not get updated and therefore will be faulty.

**Comment by DirkEilander** [comment]
Another usecase is large rotated grids, for which constructing the 2D coordinates array requires huge memory usage.

The solution mentioned above is however not in line with the current `.raster` accessor. Currently we do not save any geospatial properties in the class but rather save these in the attributes of the `spatial_ref` coordinate. The `transform` property (not `geotransform` as above) now calculates the transform on the fly from the coordinates. My preferred solution would be add a fallback option to this property to read the geotransform from the `spatial_ref` coordinate attributes in case it cannot be calculated because we have a 1D array or because the data has no coordinates (large rotated grids). Every raster method that may change the geotransform should than also write an updated transform. Compared to the current approach this is more prone to errors as failing to update the transform will result in a mislocated grid.
