### ISSUE TITLE
ENH: Solve which data catalog version to use based on the user hydromt version

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#461]
### Kind of request

Changing existing functionality

### Enhancement Description

If we would now update a predefined data catalog file based on recent developments in #438 and #334, users with a hydromt version previous to those developments would no longer be able to used that data catalog unless specifying the version with 
`DataCatalog(data_libs=[{lib}={version}])`

There are two possible solutions in my opinion:
- Selecting the last compatible data catalog version . This could happen in the `DataCatalog.from_predefined_catalogs` method. This could be done by adding the minimal hydromt version to the [predefined_catalogs.yml](https://github.com/Deltares/hydromt/blob/main/data/predefined_catalogs.yml) or loop over the data catalog files until we find a match.
- Include the data catalog files and predifined_catalog file in the release itself rather than downloading it from github. We would than need to make sure that the catalog files work with each release. However, this would limit our flexibility on how fast we can update the data catalog (add new sources etc.)

TODO decide on strategy of predefined catalogs (in release of seperate versioning on github). @hboisgon @savente93 what are your thoughts?

### Use case

see above

**Comment by savente93** [comment]
Couple quick thoughts: 
1. I'm not quite sure what you mean by "Solving the data catalog version". (no sarcasm intended) 
2. I do think that having some mechanism to HydroMT to select which catalog it should use based on version, is the correct way going forward since it strikes a nice balance between forward and backward compatibility. However, we can't back port this functionality to previous version, so we need to decide what to do with that. Do we know how many projects still use older versions? How many use older catalogs?  
3. I really like the idea of HydrMT having some compatibility checking for the data catalog, even for things outside of versioning. I think this could have very nice synergy with #236 

So taking points 2&3 into account I would favor the first solution, although some more work would need to be done there to figure out exactly how we want this. 

As a final point, I actually think that this could be RFC worthy. The stated issue is fairly simple, but I think this could have huge implications for us in the future, since this is essentially about "how do we deal with breaking changes in the catalog", so at the very least it would be good to make a record of the considerations. I'm happy to guide you through the process if you want Dirk,what do you think?

**Comment by DirkEilander** [comment]
After discussion we decided to not include the catalog files in the release which gives more flexibility to add new datasets in between releases of hydromt. Instead we will use semantic versioning in the `meta.hydromt_version` key of a catalog (see example below).  We can loop over available versions in `DataCatalog.from_predefined_catalogs`  to find a compatible version. The compatibility check should happen in `DataCatalog.from_yml`  by throwing an error if incompatible which can be catched by  `DataCatalog.from_predefined_catalogs` to try the next version until success. The function should also deal with old data catalog files which don't have a meta key

```yaml
meta:
  root: p:/wflow_global/hydromt
  version: 2023.3
  hydromt_version: ">=0.8, <0.9"  # or "^0.8.0"
```

**Comment by savente93** [comment]
- [ ] Loop over available versions in DataCatalog.from_predefined_catalogs to find a compatible version. 
- [ ] The compatibility check should happen in DataCatalog.from_yml by throwing an error if incompatible which can be catched by DataCatalog.from_predefined_catalogs to try the next version until success. 
- [ ] The function should also deal with old data catalog files which don't have a meta key

**Comment by savente93** [comment]
Note to self: distinguish between "provider_version", "catalog_version", "hydromt_version" and probably a few other ones too

**Comment by DirkEilander** [comment]
> Note to self: distinguish between "provider_version", "catalog_version", "hydromt_version" and probably a few other ones too

Saw this comment in my email. Quick reply: We have a data_version, catalog_version and hydromt_version which are relevant for the DataCatalog. We don't have a provider_version and I also don't think that's needed a.t.m.

**Comment by savente93** [comment]
I think what I called provider_version is the same as what you call data_version. it was just a note to myself, to make the distinction, but it's good to know what I should use to make things consistent. thanks
