### ISSUE TITLE
Add a debug message for ignoring user defined crs when reading raster 

### ISSUE THREAD

**Issue by xldeltares** [Deltares/hydromt#462]
### Kind of request

Changing existing functionality

### Enhancement Description

The feature improves the clarity of `RasterDatasetAdapter.get_data` method, especially for cases where local data are used. 

Current behavior:
In data_catalog.yml, when a raster file has crs in it, the user specified crs will not be used, and the user does not get a notification about this behavior. 

Expected behavior:
A debug message or a warning would be helpful to make it clear that crs specified by the user in data_catalog.yml is ignored. 

### Use case

When a user create a data_catalog.yml entry for a local data, they might input argument crs accompany the dataset. If there are mismatch between the dataset crs and argument crs, a user might have incorrectly expected the raster file would get the crs specified in the data catalogue, or they might have assigned the user raster crs by mistake.

**Comment by DirkEilander** [comment]
Good suggestion! A clear warning in case the user defined crs (or nodata) value does not match the original data would indeed be helpful. 

Currently, the crs and nodata attributes from the data catalog are only used if missing in the original data. The idea is that accidently overwriting the nodata value or crs to a value that is not matching the original data could easily cause unexpected behaviour downstream. Although with clear warning messages this issue could also be mitigated. 

What do you think is logical behaviour here @hboisgon @xldeltares ?

**Comment by hboisgon** [comment]
For me a clear warning message that the crs/nodata value in the data catalog are different than the encoded ones in the data is enough. 
With crs we should not do reprojection if the crs is different especially for gridded data without specifying a method anyhow so not too much we can do apart from a warning. For nodata you could imagine changing it but I don't know if this is useful as in hydromt we have a raster.nodata argument that makes things consistent if nodata is set properly.

I think the case is pretty rare that the encoded nodata / crs would be wrong, so then the data needs to be pre-processed before using I would say rather than hydromt changing it via the data catalog.

**Comment by xldeltares** [comment]
Hi! I agree with @hboisgon about using clear warning message (in combination with further documentation). It was a good point that the crs and nodata probably can be treated separately, as changing the former requires reprojection while changing the latter does not. 

My experience was mainly for crs. Most of time local data that comes from a local source do have correct local projection. It is more likely that the user did some pre-processing themselves which might have gone wrong.  In that case,  A clear warning message + notes in the documentation should suffice. 

For nodata, I think it is handy to to set nodata in datacatalog if the user is expecting a certain value to be written to model files. e.g. writes 0 into -999. But indeed less common.

**Comment by hboisgon** [comment]
Can be done together with issue #335
