### ISSUE TITLE
Conflict HydroMT version vs examples version

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#465]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are wrong

### Location of the documentation

https://deltares.github.io/hydromt/latest/getting_started/examples_index.html

### Documentation problem

In the docs, we asked the user to usually install hydromt with conda-forge.
But then to run the examples, we advise to clone the current dev version of the repository in order to download the jupyter notebooks.

Depending on changes (especially before releasing), the content in the examples might not work with the latest conda-release so examples would fail.
This has been reported for hydromt-wflow: https://jmp75.github.io/work-blog/

### Suggested fix for documentation

At least in the docs mention that users should download the zip folder from the hydromt release version they are using or warn that if they use main/clone they may run into problems.

Not sure if we could publish our examples more smartly, with maybe a function that would check the current installed hydromt version and downloads the right examples from there?

**Comment by DirkEilander** [comment]
That's a hard one to really solve, frequent release will partially mitigate the issue, While the examples of the last released version can be downloaded (e.g. 0.8.0 via https://github.com/Deltares/hydromt/archive/refs/tags/v0.8.0.zip) this requires updating this link at every release. The user will than also find that the notebooks are different from the ones online.

I'd be more in favor of adding a version check on top of each notebook that we update with new changes in that notebook. That way it's clear for a user that the particular notebook requires a new version. We should update the install procedure to install the last released version + example dependencies and explain how this can be updated to the last dev version with 'pip install git+https://github.com/Deltares/hydromt.git' in case a notebook gives a version error. I also noticed the examples/readme is really outdated since we moved away from maintaining an environment.yml file in the root and hence should updated asap. 

I think that binder also makes use of the latest released version (currently this still points to a binder image published on savente dockerhub account.)

TODO:
- [ ] fix binder dockerhub image to point to latest deltares image @savente93, Possibly add a step to the dockerfile to get the latest dev environment?
- [ ] update install procedure in examples/readme.rst. 
- [ ] add minimum version checks to notebooks

**Comment by DirkEilander** [comment]
Another option I just discussed with @hboisgon is to make a download examples method in hydromt  (and the CLI?) to download the examples of the installed version. This could be part of the install procedure in examples/readme.rst

**Comment by hboisgon** [comment]
Also if we do implement some code to download the examples from the installed version, could we in core also implement something that would work for the plugin versions (eg hydromt_wflow examples based on hydromt_wflow version)? Or do we have to leave that up to the plugins to reproduce what we will implement in core?

**Comment by hboisgon** [comment]
Another reason why this would be nice to support is that for easy install for non python users, we can also suggest installing using [Deltaforge](https://github.com/Deltares/deltaforge). And there depending on releases, the packages version can be older still than what is released on conda-forge (eg hydromt-wflow in deltaforge is 0.2.1 and on conda-forge 0.3.0)

**Comment by savente93** [comment]
I don't think actually that adding code to download examples is the right way. I think the easiest way by far is to make the main docs point to the docs of the latest released version, that way the docs are consistent with what is on conda forge. Now that we have a version switcher in the docs, if it is needed people who use the dev version can still choose those docs

**Comment by DirkEilander** [comment]
> I don't think actually that adding code to download examples is the right way. I think the easiest way by far is to make the main docs point to the docs of the latest released version, that way the docs are consistent with what is on conda forge. Now that we have a version switcher in the docs, if it is needed people who use the dev version can still choose those docs

I agree with your suggestion for the docs. In addition, a function that downloads the repository matching the version of your installation is not difficult right? This would make it easier for users that are not familiar with git to download and run the examples. The only thing left is that users need to install additional dependencies to run the examples (e..g jupyter)
