### ISSUE TITLE
Use of the alias in the data catalog should be removed in 1.0 

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#549]
### Kind of request

Removing existing functionality

### Enhancement Description

Use of the alias in the data catalog has been marked as deprecated for quite a while now, since the functionality has been superseded by the use of variants. Therefore the functionality for using it should be removed in the next breaking release (i.e. v1.0)

**Comment by DirkEilander** [comment]
I don't see the necessity for removing the alias any longer and I would suggest to remove the warning rather than the functionality. Besides the functionality that has been improved with the variants there is still use for it to shorten data catalogs of similar datasets which are not necessarily variants, e.g. different datasets from the same paper that share the meta data section.
