### ISSUE TITLE
Decide on the public API for v1

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#572]
### Kind of request

Changing existing functionality

### Enhancement Description

I don't know exactly what this would entail, but in the past I've heard people talk about a reorganization of the HydroMT file structure so that the top level import and external APIs are a bit better defined. I'm opening this issue to start this discussion.

**Comment by savente93** [comment]
@Jaapel is there anything left we should discuss after you merge #1029 ? I think aside from that we're mostly done here right?

**Comment by Jaapel** [comment]
Before closing I would like to still do:
- [ ] https://github.com/Deltares/hydromt/issues/983
- [ ] https://github.com/Deltares/hydromt/issues/886.

Then I would like to decide on:
- [ ] _typing: as at least `SourceMetadata` should be public
- [ ] contents of _cli
- [ ] contents of `gis`
- [ ] contents of `io`
- [ ] contents of `stats`
- [ ] contents of `utils` and `_utils`

So still quite some discussing to do. Maybe also good to check with at least Hélène on the plugin use.
Another thing I want to propose is where possible, to use keyword arguments instead of positional arguments where it makes sense, like `def function(ds: xr.Dataset, *, specific_kwarg1: Type, specific_kwarg2: Type)`, so that making backwards compatible changes is easier.

**Comment by savente93** [comment]
That's fair, then it'll just stay open for now
