### ISSUE TITLE
Soil thickness layer in soilgrids_v2.0 is in different projected CRS than other layers

### ISSUE THREAD

**Issue by Tjalling-dejong** [Deltares/hydromt#706]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

```
from hydromt import DataCatalog

datacatalog = DataCatalog("deltares_data")
datacatalog.get_rasterdataset("soilgrids_v2.0")
```

### Current behaviour

hydromt.io.open_mfraster() is used to open the rasters of the soilgrids dataset. This function checks if the rasters are identical in crs, transform and shape. If that is not the case a merge error is raised.  Soilthickness is in the Homolosine Goode projection while the other layers are in the Interrupted Homolosine Goode projection.
Whenever `get_rasterdataset("soilgrids_v2.0")` is called a Merge error will be raised because of the mismatched projections.

### Desired behaviour

`get_rasterdataset("soilgrids_v2.0")` should give no merge errors

**Comment by DirkEilander** [comment]
@hboisgon @JoostBuitink @verseve Do you remember what the status of using soilgrids_v2 in wflow is? If I remember correctly, @laurenebouaziz worked on this, but I think that because of this error it is not actually possible to use this dataset yet in wflow, or is it? And do we want to do some preprocessing on the data (I think it requires aligning all the grids) to make it work or do we prefer to continue working with v1?

@Tjalling-dejong For #667 I suggest to continue by dropping this version from the catalog for now.

**Comment by Tjalling-dejong** [comment]
Issue is closed because users do not want to use soilgrids_v2
