### ISSUE TITLE
Consistent Strategy for `NoData`

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#802]
### Kind of request

Changing existing functionality

### Enhancement Description

We can encounter no data in many places:
- MetaDataResolver: e.g. search for certain naming convention encounters no uris
- Driver: e.g. empty file
- DataAdapter: no data after slicing.

We need a consistent strategy to deal with certain situation. What do we handle where. And can you call different strategies per place where you encounter no data?

**Comment by savente93** [comment]
From my understanding, I think this will primarily be decided by the plugin developers, as which data is and isn't optional depends mostly on the model I would assume. Aside from that I think it is best to be as permissive as possible here, since users can easily make it more strict by passing arguments but making it less strict is harder. Therefore I'd suggest the following: 
- for workflow file users we expose an init/global option to set a default strategy which can then be used unless the user overrides it in a similar manner to how we handle the default file names in the components now. 
- Plugin developers can then override this behaviour by passing the correct arguments during driver/component initialisation
- Users who use the interactive python API will have to understand the consequences and pass the correct arguments themselves. 
- Everywhere else we default to `Ignore` since missing data will either not lead to any error (in which case this is no problem for the user) or it will (in which case the warning logged is about as helpful as the exception raised I think), so here we are as unobtrusive as possible in the cases where it doesn't really matter. 

What do people think?
