### ISSUE TITLE
Move `setup_grid` and `setup_mesh2d` to region component.

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#813]
### Kind of request

Changing existing functionality

### Enhancement Description

Currently GridModel and MeshModel have their own fucntionatlity to setup the region. When the new Region component and the Grid/Mesh components are merged, a new PR should be made to move this functionality from the components into the region component so that all the region definitoin logic is in one place. 

### Use case

This should make documentation and organization clearer.

**Comment by deltamarnix** [comment]
I think my PR #888 fixes this issue?

**Comment by deltamarnix** [comment]
In PR #888, this functionality was moved to workflow functions for both `workflows.mesh` and `workflows.grid`. Since there are only a couple of region kinds that actually do something similar, we have decided that it is better to let the workflows decide which types are supported and not make some magical function that appears to be doing everything.
